# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "profit-peak-ads-track"
client_id = "a60fb14ccd719f994afbe826f24976b5"
application_url = "https://trailpixel.serveo.net"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_customers,write_pixels,read_customer_events"

[auth]
redirect_urls = [
  "https://trailpixel.serveo.net/auth/callback",
  "https://trailpixel.serveo.net/auth/shopify/callback",
  "https://trailpixel.serveo.net/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "demo-profit-peak.myshopify.com"
