# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "profit-peak-ads-track"
client_id = "8cb41404f1ada8a203538ba91e394d55"
application_url = "https://d74a-45-61-160-167.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_customers,write_pixels,read_customer_events"

[auth]
redirect_urls = [
  "https://d74a-45-61-160-167.ngrok-free.app/auth/callback",
  "https://d74a-45-61-160-167.ngrok-free.app/auth/shopify/callback",
  "https://d74a-45-61-160-167.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "demo-profit-peak.myshopify.com"
