# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "profit-peak-ads-track"
client_id = "101ea4c76046514d4961f228a58397ac"
application_url = "https://lopez-tunisia-conspiracy-moderator.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_customers,write_pixels,read_customer_events"

[auth]
redirect_urls = [
  "https://lopez-tunisia-conspiracy-moderator.trycloudflare.com/auth/callback",
  "https://lopez-tunisia-conspiracy-moderator.trycloudflare.com/auth/shopify/callback",
  "https://lopez-tunisia-conspiracy-moderator.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "demo-profit-peak.myshopify.com"
