# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "profit-peak-ads-track"
client_id = "101ea4c76046514d4961f228a58397ac"
application_url = "https://supposed-specs-candidates-ceramic.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,read_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_merchant_managed_fulfillment_orders,write_third_party_fulfillment_orders,read_customers"

[auth]
redirect_urls = [
  "https://supposed-specs-candidates-ceramic.trycloudflare.com/auth/callback",
  "https://supposed-specs-candidates-ceramic.trycloudflare.com/auth/shopify/callback",
  "https://supposed-specs-candidates-ceramic.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "demo-profit-peak.myshopify.com"
